[package]
name = "dj-store"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.0-rc.5", features = ["headers"] }
chrono = "0.4"
displaydoc = "0.2.3"
dotenv = "0.15"
jsonwebtoken = { version = "8.1.1", default-features = false }
log = "0.4"
mime_guess = { version = "2", optional = true}
rand = "0.8.5"
rust-embed = { version = "6", features = ["axum"], optional = true}
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3", features = ["cors", "trace"] }
tracing-subscriber = "0.3"
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "serde"] }

[features]
default = ["embed-ui"]
embed-ui = ["dep:rust-embed", "dep:mime_guess"]
