[package]
name = "dj-store"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.0-rc.5"
chrono = "0.4"
displaydoc = "0.2.3"
dotenv = "0.15"
log = "0.4"
mime_guess = { version = "2", optional = true}
rust-embed = { version = "6", features = ["axum"], optional = true}
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3", features = ["cors", "trace"] }
tracing-subscriber = "0.3"

[features]
default = ["embed-ui"]
embed-ui = ["dep:rust-embed", "dep:mime_guess"]
