[package]
name = "dj-store"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5"
mime_guess = { version = "2", optional = true}
rust-embed = { version = "6", features = ["axum"], optional = true}
serde = { version = "1.0.145", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[features]
embed-ui = ["dep:rust-embed", "dep:mime_guess"]
