[package]
name = "api-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0"
quote = "1.0"

[lib]
proc-macro = true

[dev-dependencies]
axum = "0.6.17"
log = "0.4"
displaydoc = "0.2"
thiserror = "1.0"
