//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vote")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub user_token: DateTimeUtc,
    pub music_id: u32,
    pub vote_date: DateTimeUtc,
    pub like: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
