on:
  push:
    branches: [main]
name: Client
env:
  NODE_VERSION: 18
jobs: 
  lint:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
      - run: yarn
      - run: yarn lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
      - run: yarn
      - run: yarn build
